In [ ]:
import pandas as pd
import json
import numpy as np


df = pd.read_excel('/content/Data Spreadsheet for _Cleaning with Spreadsheets_ .xlsx', sheet_name='Sheet1')

In [ ]:

#df

In [ ]:
# Substituir NaN e NaT por "EXCLUDE"
df.fillna('EXCLUDE', inplace=True)

# Substituir "EXCLUDE" por uma string vazia ('')
df.replace('EXCLUDE', '', inplace=True)

In [ ]:
#df

In [ ]:
import numpy as np

# Substituir strings vazias por NaN
df['Total'].replace('', np.nan, inplace=True)

# Converter a coluna "Total" para números de ponto flutuante e somar
total_sum = df["Total"].astype(float).sum()

print(total_sum)

22264.100000000006

In [ ]:
df_transposed = df.transpose()

# Ou você pode usar a propriedade T
df_transposed = df.T

# Visualizar o DataFrame transposto
display(df_transposed)

,0,1,2,3,4,5,6,7,8,9,...,40,41,42,43,44,45,46,47,48,49
Number,,1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0,9.0,...,40.0,41.0,42.0,43.0,44.0,45.0,46.0,47.0,48.0,49.0
Order Date,,2019-01-06 00:00:00,2019-01-23 00:00:00,2019-02-09 00:00:00,2019-02-26 00:00:00,2019-03-15 00:00:00,,2019-04-18 00:00:00,2019-05-05 00:00:00,2019-05-22 00:00:00,...,2020-10-31 00:00:00,2020-11-17 00:00:00,2020-12-04 00:00:00,2020-12-21 00:00:00,2019-01-06 00:00:00,2019-01-23 00:00:00,2019-02-09 00:00:00,2019-02-26 00:00:00,2019-03-15 00:00:00,2019-04-01 00:00:00
Region,,East,Central,Central,Central,West,East,Central,Central,West,...,Central,Central,Central,Central,East,Central,Central,Central,East,East
Name,,Jones,Kivell,Jardine,Gill,Sorvino,Jones,Andrews,Jardine,Thompson,...,Andrews,Jardine,Jardine,Andrews,Jones,Kivell,Jones,Morgan,Sorvino,Jones
Item,,Pencil,Binder,Pencil,Pen,Pencil,Binder,Pencil,Pencil,Pencil,...,Pencil,Binder,Binder,Binder,Pen,Pencil,Binder,Desk,Pen Set,Pen Set
Units,,95.0,50.0,36.0,27.0,56.0,60.0,75.0,90.0,32.0,...,14.0,11.0,94.0,28.0,96.0,53.0,80.0,5.0,62.0,55.0
Unit Cost,,1.99,19.99,4.99,19.99,2.99,4.99,1.99,,1.99,...,1.29,4.99,19.99,4.99,4.99,1.29,8.99,125.0,4.99,12.49
Total,NaN,189.05,999.5,179.64,539.73,167.44,299.4,149.25,449.1,63.68,...,18.06,54.89,1879.06,139.72,479.04,68.37,719.2,625.0,309.38,686.95

In [ ]:
df['Total'].replace('', np.nan, inplace=True)

# Converter a coluna "Total" para números de ponto flutuante e somar
total_sum = df["Total"].astype(float).sum()

print(total_sum)

22264.100000000006